import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { readFile } from 'node:fs/promises';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const rawImportPlugin = {
	name: 'raw-imports',
	setup(build) {
		build.onResolve({ filter: /\?raw$/ }, async (args) => {
			const resolved = await build.resolve(args.path.replace(/\?raw$/, ''), {
				resolveDir: args.resolveDir,
				kind: args.kind,
			});
			return { ...resolved, namespace: 'raw' };
		});
		build.onLoad({ filter: /.*/, namespace: 'raw' }, async (args) => {
			const contents = await readFile(args.path, 'utf8');
			return { contents, loader: 'text' };
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	plugins: [rawImportPlugin],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2022',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
